/**
 * Database Types for Supabase
 * 
 * This file will be auto-generated by running:
 * npm run db:types
 * 
 * For now, here are the manual type definitions based on the migration.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type PartnerType = 'person' | 'company'
export type PartnerTitle = 'mr' | 'mrs' | 'ms' | 'dr' | 'prof' | 'other'

export interface Database {
  public: {
    Tables: {
      partner: {
        Row: {
          id: string
          user_id: string | null
          company_type: PartnerType
          is_company: boolean
          parent_id: string | null
          name: string
          display_name: string | null
          ref: string | null
          title: PartnerTitle | null
          function: string | null
          email: string | null
          phone: string | null
          mobile: string | null
          website: string | null
          street: string | null
          street2: string | null
          city: string | null
          state: string | null
          zip: string | null
          country_code: string | null
          vat: string | null
          lang: string
          tz: string
          credit_limit: number
          comment: string | null
          avatar_url: string | null
          birthdate: string | null
          barcode: string | null
          active: boolean
          created_at: string
          updated_at: string
          created_by: string | null
          updated_by: string | null
        }
        Insert: {
          id?: string
          user_id?: string | null
          company_type?: PartnerType
          parent_id?: string | null
          name: string
          display_name?: string | null
          ref?: string | null
          title?: PartnerTitle | null
          function?: string | null
          email?: string | null
          phone?: string | null
          mobile?: string | null
          website?: string | null
          street?: string | null
          street2?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          country_code?: string | null
          vat?: string | null
          lang?: string
          tz?: string
          credit_limit?: number
          comment?: string | null
          avatar_url?: string | null
          birthdate?: string | null
          barcode?: string | null
          active?: boolean
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
        }
        Update: {
          id?: string
          user_id?: string | null
          company_type?: PartnerType
          parent_id?: string | null
          name?: string
          display_name?: string | null
          ref?: string | null
          title?: PartnerTitle | null
          function?: string | null
          email?: string | null
          phone?: string | null
          mobile?: string | null
          website?: string | null
          street?: string | null
          street2?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          country_code?: string | null
          vat?: string | null
          lang?: string
          tz?: string
          credit_limit?: number
          comment?: string | null
          avatar_url?: string | null
          birthdate?: string | null
          barcode?: string | null
          active?: boolean
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'partner_user_id_fkey'
            columns: ['user_id']
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'partner_parent_id_fkey'
            columns: ['parent_id']
            referencedRelation: 'partner'
            referencedColumns: ['id']
          }
        ]
      }
      partner_category: {
        Row: {
          id: string
          name: string
          color: string
          parent_id: string | null
          active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          color?: string
          parent_id?: string | null
          active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          color?: string
          parent_id?: string | null
          active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'partner_category_parent_id_fkey'
            columns: ['parent_id']
            referencedRelation: 'partner_category'
            referencedColumns: ['id']
          }
        ]
      }
      partner_category_rel: {
        Row: {
          partner_id: string
          category_id: string
        }
        Insert: {
          partner_id: string
          category_id: string
        }
        Update: {
          partner_id?: string
          category_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'partner_category_rel_partner_id_fkey'
            columns: ['partner_id']
            referencedRelation: 'partner'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'partner_category_rel_category_id_fkey'
            columns: ['category_id']
            referencedRelation: 'partner_category'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      partner_type: PartnerType
      partner_title: PartnerTitle
    }
  }
}

// Helper types for easier usage
export type Partner = Database['public']['Tables']['partner']['Row']
export type PartnerInsert = Database['public']['Tables']['partner']['Insert']
export type PartnerUpdate = Database['public']['Tables']['partner']['Update']

export type PartnerCategory = Database['public']['Tables']['partner_category']['Row']
export type PartnerCategoryInsert = Database['public']['Tables']['partner_category']['Insert']
export type PartnerCategoryUpdate = Database['public']['Tables']['partner_category']['Update']
